l='I QYSM EOTZ IMY, OS I MIQIDG PIV, PIV IBIG... OE OC I AIVU EOTZ PYV EWZ VZJZQQOYS. IQEWYNMW EWZ AZIEW CEIV WIC JZZS AZCEVYGZA, OTFZVOIQ EVYYFC WIHZ AVOHZS EWZ VZJZQ PYVKZC PVYT EWZOV WOAAZS JICZ ISA FNVCNZA EWZT IKVYCC EWZ MIQIDG. ZHIAOSM EWZ AVZIAZA OTFZVOIQ CEIVPQZZE, I MVYNF YP PVZZAYT POMWEZVC QZA JG QNUZ CUGBIQUZV WIC ZCEIJQOCWZA I SZB CZKVZE JICZ YS EWZ VZTYEZ OKZ BYVQA YP WYEW. EWZ ZHOQ QYVA AIVEW HIAZV, YJCZCCZA BOEW POSAOSM GYNSM CUGBIQUZV, WIC AOCFIEKWZA EWYNCISAC YP VZTYEZ FVYJZC OSEY EWZ PIV VZIKWZC YP CFIKZ'
l=''.join(l.split())
l=''.join(l.split(','))
l=''.join(l.split(';'))
l=''.join(l.split('’'))
l=''.join(l.split('.'))
l=''.join(l.split('?'))
l=''.join(l.split('!'))
print(l)